config/routes.rb
Calibration::Application.routes.draw do

  resources :dependents

  resources :calibrators

  resources :events

  resources :issues

  resources :external_docs

  resources :items do
    resources :events, :issues, :dependents, :external_docs
  end

  match "item/:action", :controller => 'items', :action => /[a-z_]+/i
  
  match 'print_due_cal' => "items#printable_due_cal", :as => "print_due_cal"
  match 'in_cal' => "items#show_in_cal", :as => "in_cal"
  match "print_in_cal" => "items#printable_in_cal", :as => "print_in_cal"
  match 'inactive' => "items#show_inactive", :as => "inactive"
  match 'show_due_in_thirty_days' => "items#show_thirty_days", :as => "due_in_thirty"
  match 'print_thirty_day_report' => "items#printable_thirty_days", :as => "print_thirty"
  match 'show_due_in_sixty_days' => "items#show_sixty_days", :as => "due_in_sixty"
  match 'show_all_records' => "items#show_all_items", :as => "all_items"
  match 'show_all_items_by_cal_date' => 'items#show_all_items_by_cal_date', :as => 'all_items_by_cal_date'
  match 'all_items_by_location' => 'items#show_all_items_by_location', :as => "all_items_by_location"
  match 'show_all_issues' => "items#show_all_issues", :as => "all_issues"
  match 'show_all_events' => "items#show_all_events", :as => "all_events"
  match 'show_all_dependents' => "items#show_all_dependents", :as => "all_dependents"
  match 'show_all_documents' => "items#show_all_documents", :as => "all_documents"
  match 'search' => "items#search_remote", :as => "search"
  match 'return_from_cal/:item_id' => "events#return_from_cal", :as => "return_from_cal", :via => "get"
  root :to => "items#index"
  

  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id          :integer          not null, primary key
#  item_id     :integer
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Issue < ActiveRecord::Base
  belongs_to :item
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
   before_filter :get_item_id, :except => [ :update, :create]
   before_filter :get_item_id_params, :only => [:update, :create ]

  def get_item_id
    @item = Item.find(params[:item_id])
  end

  def get_item_id_params
    @item = Item.find( params[:issue][:item_id] )
  end

  def index
    @issues = @item.issues.all( :order => "created_at DESC" )
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  def show
    @issue = @item.issues.find( params[:id] )
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  def new
    @issue = @item.issues.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  def edit
    @issue = @item.issues.find( params[:id] )
  end

  def create
    @issue = @item.issues.create( params[:issue] )
    respond_to do |format|
      if @issue.save
        flash[:notice] = 'Issue was successfully created.'
        format.html { redirect_to(item_issues_path(@item.id) ) }
        format.xml  { render :xml => @issue, :status => :created, :location => @issue }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @issue = @item.issues.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        flash[:notice] = 'Issue was successfully updated.'
        format.html { redirect_to(item_issues_path(@item.id) ) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @issue.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
	@issue = @item.issues.find( params[:id] )
  @issue.destroy

  respond_to do |format|
    format.html { redirect_to(item_issues_path(@item.id)) }
    format.xml  { head :ok }
  end
  end


end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/edit.html.erb
<h1>Editing issue for <%= "#{h(@item.description)}"%> </h1>

<% if @issue.errors.any? %>
<h2 style="color: red"><%= pluralize(@issue.errors.count, "error") %> prohibited this event from being saved:</h2>
<ul>
<% @issue.errors.full_messages.each do |msg| %>
  <li style="color: red"><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for([ @item, @issue ]) do |f| %>
  <%= f.hidden_field :item_id %>

<table>
  <tr>
    <td><%=f.label :description%></td>
    <td><%=f.text_field :description %></td>
  </tr>
</table>
<p>
  <%= f.submit 'Update' %>
</p>
<% end %>

<p><%= link_to 'Show Issue', item_issue_path( @item.id ) %></p>
<p><%= link_to "New Issue", new_item_issue_path( @item.id ) %></p>
<p><%= link_to "Back to #{h(@item.description)}", item_path( @item ) %></p>
<p><%= link_to 'Back to Summary Page', items_path %></p>

app/views/issues/index.html.erb
<h1>Showing all Issues for <%= "#{h(@item.description)}"%> </h1>

<p><%=get_image_tag_from_item_id(@item.id) %></p>

<table>
  <tr>
    <th>Description</th>
    <th>Created At</th>
  </tr>

<% @issues.each do |issue| %>
  <tr>
    <td><%= link_to (h issue.description), edit_item_issue_path( @item.id, issue.id ) %></td>
    <% if !issue.created_at.nil? %>
      <td><%=h issue.created_at.strftime('%m/%d/%Y') %></td>
    <% end  %>
  </tr>
<% end  %>
</table>

<p><%= link_to 'New Issue', new_item_issue_path( @item.id ) %></p>
<p><%= link_to "Back to #{h(@item.description)}", item_path( @item ) %></p>
<p><%= link_to 'Back to Summary Page', items_path %></p>

app/views/issues/new.html.erb
<h1>New Issue for <%= "#{h(@item.description)}"%> </h1>

<% if @issue.errors.any? %>
<h2 style="color: red"><%= pluralize(@issue.errors.count, "error") %> prohibited this event from being saved:</h2>
<ul>
<% @issue.errors.full_messages.each do |msg| %>
  <li style="color: red"><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for([ @item, @issue ]) do |f| %>
  <%= f.hidden_field :item_id %>
<table>
  <tr>
    <td><%=f.label :description%></td>
    <td><%=f.text_field :description %></td>
  </tr>
</table>
<p>
  <%= f.submit 'Create' %>
</p>
<% end %>

<p><%= link_to 'Back to issue', item_issues_path( @item.id ) %></p>
<p><%= link_to "Back to #{h(@item.description)}", item_path( @item ) %></p>
<p><%= link_to 'Back to Summary Page', items_path %></p>

app/views/issues/show.html.erb
<h2>Showing Issue for <%= "#{@item.description} SN:#{@item.org_sn}"%></h2>

<p><%=get_image_tag_from_item_id(@issue.item_id) %></p>

<ul>
	<li>
		<em>Description:</em> <%= h @issue.description %>
	</li>
	<li>
		<em>It was created on</em> <%= h @issue.created_at.strftime('%m/%d/%Y') %>
	</li>
</ul>

<p>
	<%= link_to 'Edit', edit_item_issue_path( @item.id )%> | 
	<%= link_to 'Destroy', item_issue_path( @item.id ), :data=> { :confirm => 'Are you sure?'}, :method => :delete %> |
	<%= link_to 'New Issue', new_item_issue_path( @item.id ) %>
</p>
<p>
	<%= link_to "Back to #{h(@item.description)}", item_path( @item ) %> |
	<%= link_to 'Back to Summary Page', items_path %> |
	<%= link_to 'Back to all issues', all_issues_path%>
</p>