config/routes.rb
Calibration::Application.routes.draw do

  resources :dependents

  resources :calibrators

  resources :events

  resources :issues

  resources :external_docs

  resources :items do
    resources :events, :issues, :dependents, :external_docs
  end

  match "item/:action", :controller => 'items', :action => /[a-z_]+/i
  
  match 'print_due_cal' => "items#printable_due_cal", :as => "print_due_cal"
  match 'in_cal' => "items#show_in_cal", :as => "in_cal"
  match "print_in_cal" => "items#printable_in_cal", :as => "print_in_cal"
  match 'inactive' => "items#show_inactive", :as => "inactive"
  match 'show_due_in_thirty_days' => "items#show_thirty_days", :as => "due_in_thirty"
  match 'print_thirty_day_report' => "items#printable_thirty_days", :as => "print_thirty"
  match 'show_due_in_sixty_days' => "items#show_sixty_days", :as => "due_in_sixty"
  match 'show_all_records' => "items#show_all_items", :as => "all_items"
  match 'show_all_items_by_cal_date' => 'items#show_all_items_by_cal_date', :as => 'all_items_by_cal_date'
  match 'all_items_by_location' => 'items#show_all_items_by_location', :as => "all_items_by_location"
  match 'show_all_issues' => "items#show_all_issues", :as => "all_issues"
  match 'show_all_events' => "items#show_all_events", :as => "all_events"
  match 'show_all_dependents' => "items#show_all_dependents", :as => "all_dependents"
  match 'show_all_documents' => "items#show_all_documents", :as => "all_documents"
  match 'search' => "items#search_remote", :as => "search"
  match 'return_from_cal/:item_id' => "events#return_from_cal", :as => "return_from_cal", :via => "get"
  root :to => "items#index"
  

  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                 :integer          not null, primary key
#  item_id            :integer
#  cal_date           :datetime
#  calibrator_id      :integer
#  cost               :decimal(, )
#  po                 :string(255)
#  certs_file_name    :string(255)
#  certs_content_type :string(255)
#  certs_file_size    :integer
#  certs_updated_at   :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class Event < ActiveRecord::Base
  belongs_to :item 
  belongs_to :calibrators  # calibrators has many events
  
  has_attached_file :certs, :allow_nil => true,
                    :styles => { :medium => "300x300",
                                 :thumb => "100x100" }

  validates_attachment_content_type :certs, :content_type => ['image/jpeg', 'image/pjpeg', 'image/jpg', 'image/png', 'application/pdf'],
    :allow_nil => true

  validates_presence_of :cal_date
  validates_presence_of :calibrator_id

  scope :previous_10_events, :order => 'created_at DESC', :limit => 10
  
  def self.cost_over_year
    Event.sum(:cost, :conditions => ["created_at > ?", 1.year.ago])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # GET /events
  # GET /events.xml
  
   before_filter :get_event, :except => [ :update, :create ]
   before_filter :get_event_c_u, :only => [ :update, :create ]

  def get_event
    @item = Item.find(params[:item_id])
  end

  def get_event_c_u
    @calibrators = Calibrator.all_by_name
    @item = Item.find( params[:event][:item_id] )
  end
  
  def index
    @events = @item.events.all( :order => "cal_date DESC" )
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
	@event = @item.events.find( params[:id] )
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = @item.events.new
    @previous_events = @item.events.previous_10_events
    @calibrators = Calibrator.all_by_name

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = @item.events.find( params[:id] )
    @event.cal_date = Date.today
    @calibrators = Calibrator.all_by_name
  end

  def return_from_cal
    if @item.inCal
      #if item inCal then redirect to edit of most current cal event
      event = @item.events.first( :order => "cal_date DESC" )
      redirect_to( edit_item_event_path( @item.id, event.id ))
    end
  end

  # POST /events
  # POST /events.xml
  def create
    @event = @item.events.create( params[:event] )
    #set inCal to true, change to an option on the form?
    @previous_events = @item.events.previous_10_events
    @item.inCal = true
    @item.save
    respond_to do |format|
      if @event.save
        flash[:notice] = 'Event was successfully created. Status changed to inCal'
        format.html { redirect_to(item_events_path(@item.id) ) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = @item.events.find(params[:id])
    
    respond_to do |format|
      if @event.update_attributes(params[:event])

        if @item.inCal
          @item.last_calibrated_on = @event.cal_date
          @item.inCal = false
          @item.save
        end
        flash[:notice] = 'Event was successfully updated.'
        format.html { redirect_to(item_events_path(@item.id) ) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
	@event = @item.events.find( params[:id] )
    #@event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(item_events_path(@item.id)) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<table>
  <tr>
    <th>Item</th>
    <th>Cal date</th>
    <th>Calibrators</th>
    <th>Cost</th>
    <th>Po</th>
    <th>Certs</th>
  </tr>

<% events.each do |event| %>
  <tr>
    <td><%=link_to h(get_item_description_from_id( event.item_id ) ) , item_path( event.item_id ) %></td>
    <td><%=h event.cal_date.strftime('%m/%d/%Y') %></td>
    <td>
    <% if !event.calibrator_id.nil? %>
      <%= link_to h(get_calibrator_name( event.calibrator_id )), calibrator_path( event.calibrator_id )%> 
    <% else %>
      No Calibrator
    <% end %>
    </td>
    <td><%=h event.cost %></td>
    <td><%=h event.po %></td>
    <% if event.certs.url =~ /missing.png/ %>
      <td><%= link_to 'Missing Picture', edit_item_event_path(@item.id, event.id) %></td>
    <% else %>
      <td><%= link_to image_tag( event.certs.url(:thumb), :border => 0), event.certs.url, :target => '_blank' %></td>
    <% end %>
    <td><%= link_to 'Show', item_event_path(@item.id, event.id) %></td>
    <td><%= link_to 'Edit', edit_item_event_path(@item.id, event.id) %></td>
    <td><%= link_to 'Destroy', item_event_path(@item.id, event.id), :data=> { :confirm => 'Are you sure?'}, :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/events/edit.html.erb
<% if @item.inCal %>
   <h1>Returning <%= h @item.description %> from calibration</h1>
<% else %>
  <h1>Editing event</h1>
<% end %>

<% if @event.errors.any? %>
<h2 style="color: red"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
<ul>
<% @event.errors.full_messages.each do |msg| %>
  <li style="color: red"><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for([ @item, @event ], :html => { :multipart => true }) do |f| %>
  <%= f.hidden_field :item_id %>

  <table>
    <tr>
      <td><%= link_to "Calibrator:", new_calibrator_path %></td>
      <td>
        <%=  select_tag("event[calibrator_id]", options_from_collection_for_select(@calibrators, :id, :a_name, @event.calibrator_id)) %>
      </td>
      <td>
        <%=  link_to "Add calibrator", new_calibrator_path %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :cal_date %></td>
      <td><%= f.date_select :cal_date, :order => [:day, :month, :year] %></td>
    </tr>
    <tr>
      <td> <%= f.label :cost %></td>
      <td><%= f.text_field :cost %></td>
      <td><%= f.label :po %></td>
      <td><%= f.text_field :po %></td>
    </tr>
    <tr>
      <td>Add certs file(pdf) if available</td>
      <td>
      <% if @event.certs.url =~ /missing.png/ %>
        Missing Picture<br/>
      <% else %>
        <%= link_to image_tag( @event.certs.url(:thumb), :border => 0), @event.certs.url, :target => '_blank' %><br/>
      <% end %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :certs_updated_at %></td>
      <td><%= f.date_select :certs_updated_at, :order => [:day, :month, :year] %></td>
    </tr>
    <tr>
      <td><%= f.label 'Select certs file' %></td>
      <td><%= f.file_field :certs %></td>
    </tr>

  </table>
    <p>
    <%= f.submit 'Update' %>
    </p>
<% end %>

<%= link_to 'Show', item_event_path(@item.id, @event.id) %> |
<%= link_to 'Back', item_events_path(@item.id) %>

app/views/events/index.html.erb
<h1>Listing calibration events for <%="#{h(@item.description)}"%> </h1>

<%= render :partial => "events", :locals => { :events => @events } %>


<br />
<% if @item.inCal== false and @item.inactive == 0 %>
  <p><%= link_to 'Calibrate', new_item_event_path( @item.id ) %></p>
<% elsif @item.inCal %>
  <%= link_to 'Return from Cal', return_from_cal_path( @item.id )%>
<% end %>
<p><%= link_to "Back to #{h(@item.description)}", item_path( @item ) %></p>
<p><%= link_to 'Back to Due Cal Items', items_path %></p>
<p><%= link_to "back to In Cal Items(#{get_in_cal_count})", in_cal_path%></p>

app/views/events/new.html.erb
<h1>New event</h1>

<% if @event.errors.any? %>
<h2 style="color: red"><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
<ul>
<% @event.errors.full_messages.each do |msg| %>
  <li style="color: red"><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for([ @item, @event ], :html => { :multipart => true }) do |f| %>
  <%= f.hidden_field :item_id %>

  <table>
    <tr>
      <td><%= link_to "Calibrator:", new_calibrator_path %></td>
      <td>
        <%=  select_tag("event[calibrator_id]", options_from_collection_for_select(@calibrators, :id, :a_name)) %>
      </td>
    </tr>
    <tr>
      <td><%= f.label :cal_date %></td>
      <td><%= f.date_select :cal_date, :order => [:day, :month, :year] %></td>
    </tr>
    <tr>
      <td> <%= f.label :cost %></td>
      <td><%= f.text_field :cost %></td>
      <td><%= f.label :po %></td>
      <td><%= f.text_field :po %></td>
    </tr>
    <tr>
      <td><%= f.label 'Select certs file' %></td>
      <td><%= f.file_field :certs %></td>
    </tr>
    <tr>
      <td><%= f.label :certs_updated_at %></td>
      <td><%= f.date_select :certs_updated_at, :order => [:day, :month, :year] %></td>
    </tr>

  </table>
<br/>

  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<h2>Previous events</h2>
<%= render :partial => "events", :locals => { :events => @previous_events } %>

<p><%= link_to 'Back to events', item_events_path( @item.id ) %></p>
<p><%= link_to "Back to #{h(@item.description)}", item_path( @item ) %></p>
<p><%= link_to 'Back to Items', items_path %></p>

app/views/events/show.html.erb
<h2>Showing Event for <%= "#{@item.description} SN:#{@item.org_sn}"%></h2>

<p><%=get_image_tag_from_item_id(@event.item_id) %></p>

<ul>
	<li>
		It was calibrated on <%=h @event.cal_date.strftime('%m/%d/%Y') %> by
		 <%= link_to h(get_calibrator_name( @event.calibrator_id )), calibrator_path( @event.calibrator_id )%>
		 under PO# <%=h @event.po %> and has a yearly cost of <%=h @event.cost %>.
	</li>
	<li>
		Certs:
		<ul>
			<li>
				<% if @event.certs.url =~ /missing.png/ %>
        			<b>Missing Picture</b><br/>
    			<% else %>
        			<b><%= link_to image_tag( @event.certs.url(:thumb), :border => 0), @event.certs.url, :target => '_blank' %></b><br/>
    			<% end %>
			</li>
			<li>
    			<% if not @event.certs_updated_at.nil? %>
    				(Certs updated on <%=h @event.certs_updated_at.strftime('%m/%d/%Y') %>)
    			<% else %>
    	    		<b>no update date</b>
	    		<% end %>
			</li>
		</ul>
	</li>
</ul>
<% if @item.inCal %>
  <%= link_to 'Return from Cal', :controller => "event", :action => "return_from_cal", :id => @item.id %>
<% end %>

<%= link_to 'Edit', edit_item_event_path(@item.id, @event.id) %> |
<%= link_to 'Back', item_events_path(@item.id) %> |
<%= link_to "Back to #{h(@item.description)}", item_path( @item ) %> |
<%= link_to "Back to all events list", all_events_path %>