config/routes.rb
Calibration::Application.routes.draw do

  resources :dependents

  resources :calibrators

  resources :events

  resources :issues

  resources :external_docs

  resources :items do
    resources :events, :issues, :dependents, :external_docs
  end

  match "item/:action", :controller => 'items', :action => /[a-z_]+/i
  
  match 'print_due_cal' => "items#printable_due_cal", :as => "print_due_cal"
  match 'in_cal' => "items#show_in_cal", :as => "in_cal"
  match "print_in_cal" => "items#printable_in_cal", :as => "print_in_cal"
  match 'inactive' => "items#show_inactive", :as => "inactive"
  match 'show_due_in_thirty_days' => "items#show_thirty_days", :as => "due_in_thirty"
  match 'print_thirty_day_report' => "items#printable_thirty_days", :as => "print_thirty"
  match 'show_due_in_sixty_days' => "items#show_sixty_days", :as => "due_in_sixty"
  match 'show_all_records' => "items#show_all_items", :as => "all_items"
  match 'show_all_items_by_cal_date' => 'items#show_all_items_by_cal_date', :as => 'all_items_by_cal_date'
  match 'all_items_by_location' => 'items#show_all_items_by_location', :as => "all_items_by_location"
  match 'show_all_issues' => "items#show_all_issues", :as => "all_issues"
  match 'show_all_events' => "items#show_all_events", :as => "all_events"
  match 'show_all_dependents' => "items#show_all_dependents", :as => "all_dependents"
  match 'show_all_documents' => "items#show_all_documents", :as => "all_documents"
  match 'search' => "items#search_remote", :as => "search"
  match 'return_from_cal/:item_id' => "events#return_from_cal", :as => "return_from_cal", :via => "get"
  root :to => "items#index"
  

  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id                   :integer          not null, primary key
#  description          :string(255)
#  mfgr                 :string(255)
#  pn                   :string(255)
#  org_sn               :string(255)
#  mfgr_sn              :string(255)
#  location             :string(255)
#  cal_cycle_days       :integer          default(365)
#  last_calibrated_on   :date
#  inCal                :boolean          default(FALSE)
#  inactive             :integer          default(0)
#  picture_file_name    :string(255)
#  picture_content_type :string(255)
#  picture_file_size    :integer
#  picture_updated_at   :datetime
#  created_at           :datetime
#  updated_at           :datetime
#

class Item < ActiveRecord::Base
 attr_accessible :picture, :description, :mfgr, :pn
 attr_accessible :org_sn, :mfgr_sn, :location, :cal_cycle_days, :last_calibrated_on
 attr_accessible :inactive, :inCal
 attr_accessible :per_page

 @@per_page = 10
 
 has_attached_file :picture, 
                   :styles => { :thumb => "50x50",
                                :small => "100x100",
                                :medium => "300x300"
                                }
 
  validates_attachment_content_type :picture, :content_type => ['image/jpeg',
    'image/jpg', 'image/png'], :allow_nil => true

  has_many :events, :dependent => :destroy
  has_many :dependents, :dependent => :destroy
  has_many :issues, :dependent => :destroy
  has_many :external_docs, :dependent => :destroy

  validates_presence_of :description
  validates_presence_of :pn
  validates_presence_of :org_sn
  validates_presence_of :cal_cycle_days

  scope :inactive, :conditions => ["inactive = ?", 1], :order => :last_calibrated_on
  scope :in_cal, :conditions => ["inCal = ? and inactive = ?", true, 0],
        :order => :last_calibrated_on
  scope :not_in_cal, :conditions => ["inCal = ? and inactive = ?", false, 0],
        :order => :last_calibrated_on

  def self.due_cal
    not_in_cal.all( :conditions => ["(julianday('now') - julianday(items.last_calibrated_on)) >= items.cal_cycle_days"],
        :order => :last_calibrated_on ) || []
  end

  def self.due_in( number_of_days )
    cal_list = not_in_cal.all
    result_list = []
    for item in cal_list 
      if ((item.last_calibrated_on > Date.today - item.cal_cycle_days.days) and
        (item.last_calibrated_on < Date.today - (item.cal_cycle_days - number_of_days)))
        result_list << item 
      end 
    end
    result_list
#    not_in_cal.all( 
#      :conditions => ["last_calibrated_on between date('now', '-cal_cycle_days days') and date('now', '-cal_cycle_days days') , '-? days' )", 
#       number_of_days  
#      ])
    #SELECT * FROM members WHERE membership_date < date('now', '-3 months');
#    not_in_cal.all( 
#      :conditions => ["last_calibrated_on between ? and ?", 
#      Date.today - cal_cycle_days.days,
#      Date.today - ( cal_cycle_days - number_of_days ).days 
#      ])
    
    #might need to do sql datediffs?  
    #not_in_cal.all( :conditions => ["(julianday('now') - julianday(last_calibrated_on)) - ( cal_cycle_days - #{number_of_days + 1} )  < 0 and " +
    #        "(julianday('now') - julianday(last_calibrated_on)) - ( cal_cycle_days - #{number_of_days } ) >= 0"],
    #      :order => :last_calibrated_on )
  end
  
  #Item.find( :all, :conditions => ["last_calibrated_on between ? and ?", Date.today - 3.months, Date.today])
end

app/controllers/items_controller.rb
require 'will_paginate/array'
class ItemsController < ApplicationController
  before_filter :get_item

  def get_item
    @item = Item.first
    if @item.nil?
      @item = Item.new
      @item.description = 'first'
      @item.pn = 'test'
      @item.org_sn = '1234'
      @item.cal_cycle_days = 365
      @item.last_calibrated_on = Time.now
      @item.save
    end

  end
  # GET /items
  # GET /items.xml
  def index
    @items = Item.due_cal.paginate :page => params[:page], :per_page => 10
    @issues = Issue.order( 'created_at DESC' ).limit( 10 ).all
    @events = Event.order( 'created_at DESC' ).limit( 10 ).all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @items }
    end
  end

  # GET /items/1
  # GET /items/1.xml
  def show
    @item = Item.find(params[:id])
    @issues = @item.issues.all(:order => 'created_at DESC')
    @dependents = @item.dependents.all( :order => 'created_at DESC')
    @event = @item.events.first( :order => 'created_at DESC' )
    @documents = @item.external_docs.all( :order => 'created_at DESC')
    @cost = @item.events.sum( :cost, :conditions => ["created_at > ?", 1.year.ago] ).to_f
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/new
  # GET /items/new.xml
  def new
    @item = Item.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @item }
    end
  end

  # GET /items/1/edit
  def edit
    @item = Item.find(params[:id])
  end

  # POST /items
  # POST /items.xml
  def create
    @item = Item.create(params[:item])

    respond_to do |format|
      if @item.save
        flash[:notice] = 'Item was successfully created.'
        format.html { redirect_to(@item) }
        format.xml  { render :xml => @item, :status => :created, :location => @item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /items/1
  # PUT /items/1.xml
  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update_attributes(params[:item])
        flash[:notice] = 'Item was successfully updated.'
        format.html { redirect_to(@item) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.xml
  def destroy
    puts "in destroy"
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html { redirect_to(items_url) }
      format.xml  { head :ok }
    end
  end

  def search_remote
    @item = Item.first
    if params[:description] or params[:sn]
      search_term = params[:description]
      if search_term.length < 1
        search_term = params[:sn]
        search_term = '%' + search_term + '%'
        @search_results = Item.all( :conditions => ["org_sn LIKE ?", search_term])
      else
        search_term = '%' + search_term + '%'
        @search_results = Item.all( :conditions => ["description LIKE ?", search_term])
      end
    end
    respond_to do |format|
      format.html # search_remote.html.erb
      format.xml  { render :xml => @search_results }
    end

  end

  def issue_remote
    @issues = Issue.all( :order => 'created_at DESC' )
    render 'issues', :locals => { :issues => @issues }
  end

  def dependent_remote
    @dependents = Dependent.all( :order => 'item_id')
    render 'dependents', :locals => {:dependents => @dependents}
  end

  def show_thirty_days
    @items = Item.due_in( 30 ).paginate :page => params[:page], :per_page => 10
    @test_thirty_days = @items.size
  end

  def show_all_dependents
    @dependents = Dependent.all( :order => 'item_id').paginate :page => params[:page], :per_page => params[:per_page], :per_page => 15
  end

  def show_all_items
    @items = Item.all( :order => :description ).paginate :page => params[:page], :per_page => params[:per_page], :per_page => 15
  end
  
  def show_all_items_by_cal_date
    @items = Item.all( :order => 'last_calibrated_on DESC' ).paginate :page => params[:page], :per_page => params[:per_page], :per_page => 15
  end
  
  def show_all_issues
    @issues = Issue.all( :order => 'created_at DESC').paginate :page => params[:page], :per_page => params[:per_page], :per_page => 15
  end

  def show_sixty_days
    @items = Item.due_in( 60 ).paginate :page => params[:page], :per_page => 10
  end

  def show_inactive
    @items = Item.inactive.paginate :page => params[:page], :per_page => params[:per_page]
  end

  def show_in_cal
    @items = Item.in_cal.paginate :page => params[:page], :per_page => params[:per_page]
  end

  def printable_due_cal
    @due_cal = Item.due_cal
    respond_to do |format|
      format.html { render 'printable_due_cal', :layout => false }   # printable_due_cal.html.erb
      format.xml  { render :xml => @due_cal }
    end
  end

  def printable_in_cal
    @in_cal = Item.in_cal
    respond_to do |format|
      format.html { render 'printable_in_cal', :layout => false }   # printable_in_cal.html.erb
      format.xml  { render :xml => @in_cal }
    end
  end

  def printable_thirty_days
    @thirty_days = Item.due_in( 30 )
    respond_to do |format|
      format.html { render 'printable_thirty_days', :layout => false }   # printable_thirty_days.html.erb
      format.xml  { render :xml => @thirty_days }
    end
  end

  def show_all_events
    @events = Event.all( :order => 'cal_date DESC').paginate :page => params[:page], :per_page => params[:per_page], :per_page => 20

    respond_to do |format|
      format.html { render 'show_all_events' }
      format.xml {render :xml => @events }
    end
  end
  
  def show_all_documents
    @documents = ExternalDoc.all( :order => 'item_id, updated_at').paginate :page => params[:page], :per_page => params[:per_page], :per_page => 20
    
    respond_to do |format|
      format.html #show_all_documents.hrml.erb
      format.xml {render :xml => @documents }
    end
  end
  
  def show_all_items_by_location
    @items = Item.all( :order => :location ).paginate :page => params[:page], :per_page => params[:per_page], :per_page => 15
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  def show_sn_and_last_cal( item )
    raw( "The Serial Number is #{ item.org_sn } " +
      "and it is/was due cal on #{ h (item.last_calibrated_on + item.cal_cycle_days.days).strftime('%m/%d/%Y')}" )
  end
end

app/views/items/_group.html.erb
<table>
  <tr>
    <th>Description</th>
    <th>Org sn</th>
    <th>Location</th>
    <th>Last Cal</th>
    <th>Due Cal</th>
    <th>Picture</th>
  </tr>
<% aGroup.each do |item| %>
  <tr>
    <td><%=link_to h(item.description), item_events_path( item.id ) %></td>
    <td><%=h item.org_sn %></td>
    <td><%=h item.location %></td>
    <td>
      <% if item.last_calibrated_on.nil? %>
    No data
      <% else %>
    <%= "#{ h item.last_calibrated_on.strftime('%m/%d/%Y')}" %>
      <% end %>
    </td>
    <td>
      <% if item.last_calibrated_on.nil? %>
    No last cal on date
      <% else %>
    <%= "#{ h (item.last_calibrated_on + item.cal_cycle_days.days).strftime('%m/%d/%Y')}" %>
      <% end %>
    </td>
    <% if item.picture.url =~ /missing.png/ %>
      <td><%= link_to 'No Image', edit_item_path(item) %></td>
    <% else %>
      <td><%= link_to image_tag( item.picture.url(:thumb), :border=> 0), item.picture.url, :target => '_blank' %></td>
    <% end %>
    <% unless to_print == 'yes' %>
      <td>
          <%= link_to 'Show', item %>
          <%= link_to 'Edit', edit_item_path(item) %>
          <% if item.inCal %>
            <%= link_to 'Return from Cal', :controller => "event", :action => "return_from_cal", :id => item.id %>
          <% elsif item.inactive == 0 %>
            <%= link_to 'Calibrate', new_item_event_path( item ) %>
          <% end %>
          <%= link_to 'Delete', item, :data=> {:confirm => 'Are you sure?'}, :method => :delete %>
      </td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

app/views/items/_search_remote.html.erb
<h2>
  Search Results
</h2>
<table>
  <tr>
    <th>Description</th>
    <th>Org sn</th>
    <th>Location</th>
    <th>Last Cal</th>
    <th>Due Cal</th>
    <th>Picture</th>
  </tr>
<% aGroup.each do |item| %>
  <tr>
    <td><%=link_to h(item.description), item %></td>
    <td><%=h item.org_sn %></td>
    <td><%=h item.location %></td>
    <td><%= "#{ h item.last_calibrated_on.strftime('%m/%d/%Y')}" %></td>
    <td><%= "#{ h item.last_calibrated_on + item.cal_cycle_days.days}" %></td>
    <% if item.picture.url =~ /missing.png/ %>
      <td>No Image</td>
    <% else %>
      <td><%= link_to image_tag( item.picture.url(:thumb), :border=> 0), item.picture.url, :target => '_blank' %></td>
    <% end %>
  </tr>
<% end %>
</table>

app/views/items/index.html.erb
<h1>Calibration: Main Page</h1>

<h2><a name="DueCal">Due Cal</a></h2>

<div class="due_cal">
	
	<div class="digg_pagination">
    	<div clas="page_info">
      		<%= page_entries_info @items %>
    	</div>
    	<%= will_paginate @items, :container => false %>
	</div>

	<%= render :partial => 'items', :collection => @items %>

	<div class="digg_pagination">
    	<div clas="page_info">
      	<%= page_entries_info @items %>
    	</div>
    	<%= will_paginate @items, :container => false %>
	</div>
</div>

<div class="summary_info">
	<h3><%= link_to "Last 10 Issues", all_issues_path%></h3>
	<% if @issues.any? %>
		<% @issues.each do |issue| %>
			<ul>
				<%= render partial: "issues", locals: {issue: issue}%>
				<hr/>
			</ul>
		<% end %>
	<% else %>
		No Issues to Show
	<% end %>

	<h3><%= link_to "Last 10 Events", all_events_path%> </h3>
	<% if @events.any? %>
		<% @events.each do |event| %>
			<ul>
				<%= render partial: "events", locals: {event: event}%>
				<hr/>
			</ul>
		<% end %>
	<% else %>
		No Events to display
	<% end %>
</div>

app/views/items/issues.html.erb
<h2>Issues Sorted by Date</h2>
<table>
  <tr>
    <th>Item</th>
    <th>Issue</th>
    <th>Created At</th>
  </tr>
<% issues.each do |issue| %>
  <tr>
    <td><%=link_to h(get_item_description_from_id( issue.item_id ) ) , item_path( issue.item_id ) %></td>
    <td><%= h issue.description %></td>
    <td><%= h issue.created_at.strftime('%m/%d/%Y') %></td>
  </tr>
<% end %>
</table>

<% issues.each do |issue| %>
<ul>
	<li><%=link_to h(get_item_description_from_id( issue.item_id ) ) , item_path( issue.item_id ) %></li>
</ul>

app/views/items/new.html.erb
<h1>New item</h1>

<% if @item.errors.any? %>
<h2 style="color: red"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
<ul>
<% @item.errors.full_messages.each do |msg| %>
  <li style="color: red"><%= msg %></li>
<% end %>
</ul>
<% end %>

<%= form_for @item, :html => { :multipart => true } do |f| %>

<table>
  <tr>
    <td><%= f.label :description %></td>
    <td><%= f.text_field :description %></td>
  </tr>
  <tr>
    <td><%= f.label :mfgr %></td>
    <td><%= f.text_field :mfgr %></td>
  </tr>
  <tr>
    <td><%= f.label :pn %></td>
    <td><%= f.text_field :pn %></td>
  </tr>
  <tr>
    <td><%= f.label :org_sn %></td>
    <td><%= f.text_field :org_sn %><td>
  </tr>
  <tr>
    <td><%= f.label :mfgr_sn %></td>
    <td><%= f.text_field :mfgr_sn %></td>
  </tr>
  <tr>
    <td><%= f.label :location %></td>
    <td><%= f.text_field :location %></td>
  </tr>
  <tr>
    <td><%= f.label :cal_cycle_days %></td>
    <td><%= f.text_field :cal_cycle_days, :value => 365 %></td>
  </tr>
  <tr>
    <td><%= f.label :last_calibrated_on %></td>
    <td><%= f.date_select :last_calibrated_on, :order => [:day, :month, :year] %></td>
  </tr>
  <tr>
    <td><%= f.radio_button :inactive, 0, :checked => true %>Active</td>
    <td><%= f.radio_button :inactive, 1 %>Inactive</td>
  </tr>
  <tr>
    <td><%= f.radio_button :inCal, "false", :checked => true %>Not In Cal</td>
    <td><%= f.radio_button :inCal, "true" %>In Cal</td>
  </tr>
  <tr>
    <td><%= f.label :picture_file_name %><td/>
  </tr>
  <tr>
    <td><%= f.file_field :picture, :size => 10 %></td>
  </tr>
  <tr>
    <td><%= f.label :picture_updated_at %></td>
    <td><%= f.date_select :picture_updated_at, :order => [:day, :month, :year] %></td>
  </tr>
  <tr>
    <td><%= f.submit 'Create' %></td>
  </tr>
</table>
<% end %>

<%= link_to 'Back', items_path %>

app/views/items/printable_due_cal.html.erb
<h2>Due Calibration Report</h2>
<%= "Printed on #{Date.today}" %>
<br/>
&nbsp
<%= render :partial => "group", :locals => { :aGroup => @due_cal, :to_print => 'yes' }, :layout => false %>

app/views/items/printable_in_cal.html.erb
<h2>In Calibration Report</h2>
<%= "Printed on #{Date.today}" %>
<br/>
&nbsp
<%= render :partial => "group", :locals => { :aGroup => @in_cal, :to_print => 'yes' }, :layout => false %>

app/views/items/printable_thirty_days.html.erb
<h2>Due in Thirty Days Report</h2>
<%= "Printed on #{Date.today}" %>
<br/>
&nbsp
<%= render :partial => "group", :locals => { :aGroup => @thirty_days, :to_print => 'yes' }, :layout => false %>

app/views/items/show_all_events.html.erb
<h3>Showing all Events (Latest events first)</h3>

<div class="digg_pagination">
    <%= will_paginate @events, :container => false %>
</div>

<p/>

	<% @events.each_with_index do |event, index | %>

			<%= render partial: "events", locals: {event: event }%>

	<% end %>

<p/>

<div class="digg_pagination">
    <%= will_paginate @events, :container => false %>
</div>

app/views/items/show_all_issues.html.erb
<h3>Showing all Issues (Latest issues first)</h3>

<div class="digg_pagination">
    <%= will_paginate @issues, :container => false %>
</div>

<p/>

<% if @issues.any? %>
	
		<% @issues.each_with_index do | issue, index |%>

  			<%= render partial: 'issues', :locals => { issue: issue } %>	
			<hr />
		<% end %>
<% else %>
	<p>no Issues to Show</p>
<% end %>

<p/>

<div class="digg_pagination">
    <%= will_paginate @issues, :container => false %>
</div>

app/views/items/show_all_items_by_location.html.erb
<h2>Showing all Items in location order</h2>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => false %>
</div>


<%= render :partial => 'items', :collection => @items %>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => false %>
</div>

app/views/items/show_in_cal.html.erb
<h2>Showing Items Currently in cal</h2>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => true %>
</div>

<%= render :partial => 'items', :collection => @items %>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => true %>
</div>

app/views/items/show_thirty_days.html.erb
<h2>Showing Items Due Cal in 30 days</h2>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => false %>
</div>


<%= render :partial => 'items', :collection => @items %>

<div class="digg_pagination">
    <div clas="page_info">
      <%= page_entries_info @items %>
    </div>
    <%= will_paginate @items, :container => false %>
</div>

app/views/items/test_loader.html.erb
<h2>woot</h2>