config/routes.rb
Calibration::Application.routes.draw do

  resources :dependents

  resources :calibrators

  resources :events

  resources :issues

  resources :external_docs

  resources :items do
    resources :events, :issues, :dependents, :external_docs
  end

  match "item/:action", :controller => 'items', :action => /[a-z_]+/i
  
  match 'print_due_cal' => "items#printable_due_cal", :as => "print_due_cal"
  match 'in_cal' => "items#show_in_cal", :as => "in_cal"
  match "print_in_cal" => "items#printable_in_cal", :as => "print_in_cal"
  match 'inactive' => "items#show_inactive", :as => "inactive"
  match 'show_due_in_thirty_days' => "items#show_thirty_days", :as => "due_in_thirty"
  match 'print_thirty_day_report' => "items#printable_thirty_days", :as => "print_thirty"
  match 'show_due_in_sixty_days' => "items#show_sixty_days", :as => "due_in_sixty"
  match 'show_all_records' => "items#show_all_items", :as => "all_items"
  match 'show_all_items_by_cal_date' => 'items#show_all_items_by_cal_date', :as => 'all_items_by_cal_date'
  match 'all_items_by_location' => 'items#show_all_items_by_location', :as => "all_items_by_location"
  match 'show_all_issues' => "items#show_all_issues", :as => "all_issues"
  match 'show_all_events' => "items#show_all_events", :as => "all_events"
  match 'show_all_dependents' => "items#show_all_dependents", :as => "all_dependents"
  match 'show_all_documents' => "items#show_all_documents", :as => "all_documents"
  match 'search' => "items#search_remote", :as => "search"
  match 'return_from_cal/:item_id' => "events#return_from_cal", :as => "return_from_cal", :via => "get"
  root :to => "items#index"
  

  

  match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_calibration.html.erb
<li>
	Calibration
	<ul>
		<li>
			<%= link_to 'Summary Page', items_path%>
		</li>
		<li>
			<%= link_to "Due Cal(#{get_rough_due_cal_count})", items_path( :anchor => "DueCal")%>
		</li>
		<li>
			<%= link_to "In Cal(#{get_in_cal_count})", in_cal_path %>
		</li>
		<li>
			<%= link_to "Inactive(#{get_inactive_count})", inactive_path %>
		</li>
		<li>
			<%= link_to "Due in thirty days", due_in_thirty_path %>
		</li>
		<li>
			<%= link_to "Due in 60 days", due_in_sixty_path %>
		</li>
		<li>
			<%= link_to "All Records(#{get_item_count})", all_items_path %>
		</li>
		<li>
			<%= link_to "All by location", all_items_by_location_path%>
		</li>
		<li>
			<%= link_to "All by Cal Date", all_items_by_cal_date_path%>
		</li>
		<li>
			<%= link_to "Issues", all_issues_path %>
		</li>
		<li>
			<%= link_to "Dependents", all_dependents_path %>
		</li>
		<li>
			<%= link_to "All Events", all_events_path %>
		</li>
		<li>
			<%= link_to "All Documents", all_documents_path %>
		</li>
		<li>
			<%= link_to "Add an item", new_item_path %>
		</li>
	</ul>
</li>

app/views/layouts/_reports.html.erb
<li>
	Reports
	<ul>
		<li>
			<%= link_to "Due Cal Report", print_due_cal_path %>
		</li>
		<li>
			<%= link_to "In Cal Report", print_in_cal_path %>
		</li>
		<li>
			<%= link_to "Thirty days report", print_thirty_path %>
		</li>
	</ul>
</li>

app/views/layouts/_search.html.erb
<li>
	Search
	<ul>
		<%= form_for @item, :url => { :controller => "items", :action => "search_remote", :token => 'search_remote', :remote => true } do %>
		<li>
			Description:
		</li>
		<li>
			<%= text_field_tag "description",'', :size => 5 %>
		</li>
		<li>
			Serial Number:
		</li>
		<li>
			<%= text_field_tag "sn", '',:size => 5 %>
		</li>
		<li>
			<%= submit_tag 'find' %>
		</li>
		<% end %>
	</ul>
</li>

app/views/layouts/_vendors.html.erb
<li>
	Vendors
	<ul>
		<li>
			<%= link_to "List Vendors", calibrators_path %>
		</li>
		<li>
			<%= link_to "New Vendor", new_calibrator_path %>
		</li>
	</ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calibration</title>
  <% #do I need to change the stylesheet tag to application too? %>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="navbar">
    <ul>
      <%= render "layouts/calibration"%>
      <%= render "layouts/reports"%>
    </ul>
    <ul>
      <%= render "layouts/vendors"%>
    </ul>
	<ul>
	  <%= render "layouts/search"%>
	</ul>

  </div>
<div id="content">
  <p style="color: green"><%= flash[:notice] %></p>
  <p style="color: red"><%= flash[:error] %></p>
  <%= yield %>
</div>
</body></html>